### PR TITLE
Stage react api

### PR DESCRIPTION
**Pull request by tcmaraist**
Pull request for project review. This project is able to search the NASA images api as intended and return images and descriptors. It is also responsive to screen size.

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Great job with your diploma project, looks quite good! Some issues require your attention, however.

# Summary:
### Performance Criteria

#### Markup and JSX
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions. There is no horizontal scrolling on resolutions of `320px` and up. The scrollbar can't be hidden using the `overflow: hidden` declaration.

* Preloader is displayed below footer http://joxi.ru/VrwkG4GhopkQMr. Besides, on page loading preloader is loaded too, without search.

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* "Not found" block can't be displayed.

- [x]  Buttons, forms, and modal windows from the UI toolkit are used.

* Search button and form don't correspond to UI toolkit

- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* `header__title` shouldn't be a div

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.

* preloader has `absolute` positioning, it should have a parent with `relative`

- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

#### React
- React components:
  - [x]  Hooks are not used inside conditional statements or loops.
  - [x]  Hooks are called in a component's main function.
  - [x]  For class components, effects are described inside the component lifecycle methods.
- [x]  Asynchronous API requests:
  - Requests can be made through the Fetch API or by using XMLHttpRequest. Third-party libraries (such as axios or jQuery) are not used.
  - API requests are contained in a separate file.
  - The chain for processing promises ends with a `catch()` block.
  - The first `then()` handler returns `res.json`.
- [x]  Naming:
  - camelCase is used for function and variable names.
  - Only nouns are used as variable names.
  - Variable names clearly describe what is stored in them. If the project has several variables with similar data, then those variables have unique but descriptive names.
  - Descriptive names are used for functions, which reflect what they do.
  - Function names start with a verb.
  - JS classes and functional components are named using nouns and start with a capital letter.
  - Names must not include inappropriate or unclear abbreviations.
  - Сustom hook names start with `use`
- [x]  No third-party JavaScript libraries are used unless absolutely necessary. If third-party libraries are connected, then they are used appropriately.

### Best Practices

#### Markup and JSX
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

#### React
- [x]  The initial state of state variables contain the correct data type.
- [x]  API requests are described inside the `App` component.
- [x]  There is no memory leak when hanging handlers. All handlers added with addEventListener are removed when the component is unmounted.
- [ ]  API error handling:
  - [ ] The user receives a message in case of an error.
- [x]  Non-variable values (hard-coded constants) are named in all capital letters and stored in a separate configuration file.
- [x]  If you are using popups, then correct the opening and closing functionality is implemented. Popups can be closed by clicking on the cross button, overlay, or by pressing the ESC key.

### Recommendations

#### Markup and JSX
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.

* `details__image` empty alt

- [x]  Raster and vector images have been optimized.

#### React
- [x]  For internal links in the application, components from the react-router library are used.
- [x]  Semantically correct blocks are used for components. No `<div />` or other unnecessary HTML tags are used for components that consist of single-level blocks.
- [x]  The code is clean and easy to understand:
  - The code is readable and structured clearly. Some parts of the code are explained with comments if needed.
  - There is no extra code: for example, a variable is declared but not used, or there is some kind of redundant logic.
  - The code is formatted in the same way, the indentation hierarchy is respected.
  
* Redundant component ModalWithPopup

## Number of points: 69

## Additional comments:

Please fix css validation errors: http://joxi.ru/V2Vw0Z0CBpqngA http://joxi.ru/krDvaXaTGQxlM2

**Comment by tcmaraist** [comment]
Updated after first review. Website design now reflects more accurately UI toolkit in figma. Cards in Main.js now have title and description. Corrected css errors. Fixed preloader. Attached fonts with @font-face.

**Comment by ImaliaNsk** [comment]
Hello! I'm very sorry, but I have to reject the project without a review this time (you don't spend an iteration). The reason is that README.md doesn't have a link to your deployed application. Please, add. I'm very sorry I have missed this issue the previous time.

I'd also like to point out some other issues that would be better fixed in your app:

* Preloader shouldn't be displayed on page loading, it's needed only when the search is run, while waiting response from the api. Results shouldn't appear either, only after the user has made the search.
* Too many results are displayed on the site at once. This is not very convenient, because the user needs to scroll down a lot, especially on mobile screens. Please, limit the amount of loaded results (there should be 3 items according to the assignment), and use button "Show more" in case the user needs more results.
* Content should be centered on all screens: http://joxi.ru/12MwyqyCgp5kqr http://joxi.ru/8AnK1e1UNYO7Pr http://joxi.ru/Q2KwkNkCOnBwk2. The second screenshot also shows the issue with search form on mobile screens: there should be side margins, now the content sticks to the screen sides.
* "Not found" block can't be displayed - in case nothing has been found, the user should get a message about it.
* App component doesn't have a folder.
* User should received a message in case of an error.

Good luck!

**Comment by ImaliaNsk** [comment]
Hello! The project is accepted, congratulations! I wish you good luck in your further projects!

# Summary:
### Performance Criteria

#### Markup and JSX
- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions. There is no horizontal scrolling on resolutions of `320px` and up. The scrollbar can't be hidden using the `overflow: hidden` declaration.

* Preloader shouldn't be displayed on page loading, it's needed only when the search is run, while waiting response from the api. Results shouldn't appear either, only after the user has made the search.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Buttons, forms, and modal windows from the UI toolkit are used.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [ ]  The markup has been moved into the corresponding components.
  
  * noResults markup hasn't been moved to the correspondent component.
  
- [ ]  Your project contains:
  - [x] An `images`
  - [ ] A `components` folder with JS and CSS files for the components.
  
  * noResults component doesn't have a js implementation in its folder.
  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

#### React
- React components:
  - [x]  Hooks are not used inside conditional statements or loops.
  - [x]  Hooks are called in a component's main function.
  - [x]  For class components, effects are described inside the component lifecycle methods.
- [x]  Asynchronous API requests:
  - Requests can be made through the Fetch API or by using XMLHttpRequest. Third-party libraries (such as axios or jQuery) are not used.
  - API requests are contained in a separate file.
  - The chain for processing promises ends with a `catch()` block.
  - The first `then()` handler returns `res.json`.
- [x]  Naming:
  - camelCase is used for function and variable names.
  - Only nouns are used as variable names.
  - Variable names clearly describe what is stored in them. If the project has several variables with similar data, then those variables have unique but descriptive names.
  - Descriptive names are used for functions, which reflect what they do.
  - Function names start with a verb.
  - JS classes and functional components are named using nouns and start with a capital letter.
  - Names must not include inappropriate or unclear abbreviations.
  - Сustom hook names start with `use`
- [x]  No third-party JavaScript libraries are used unless absolutely necessary. If third-party libraries are connected, then they are used appropriately.

### Best Practices

#### Markup and JSX
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

#### React
- [x]  The initial state of state variables contain the correct data type.
- [x]  API requests are described inside the `App` component.
- [x]  There is no memory leak when hanging handlers. All handlers added with addEventListener are removed when the component is unmounted.
- [ ]  API error handling:
  - [ ] The user receives a message in case of an error.
- [x]  Non-variable values (hard-coded constants) are named in all capital letters and stored in a separate configuration file.
- [x]  If you are using popups, then correct the opening and closing functionality is implemented. Popups can be closed by clicking on the cross button, overlay, or by pressing the ESC key.

### Recommendations

#### Markup and JSX
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

#### React
- [x]  For internal links in the application, components from the react-router library are used.
- [x]  Semantically correct blocks are used for components. No `<div />` or other unnecessary HTML tags are used for components that consist of single-level blocks.
- [x]  The code is clean and easy to understand:
  - The code is readable and structured clearly. Some parts of the code are explained with comments if needed.
  - There is no extra code: for example, a variable is declared but not used, or there is some kind of redundant logic.
  - The code is formatted in the same way, the indentation hierarchy is respected.

## Number of points: 83

**Pull request merged**
